# Generated by Django 2.0.5 on 2018-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0002_auto_20180709_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='reason_for_laeve',
            new_name='reason_for_leave',
        ),
        migrations.AlterField(
            model_name='leave',
            name='from_session',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_session',
            field=models.IntegerField(null=True),
        ),
    ]
