# Generated by Django 2.0.5 on 2018-07-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0005_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
