# Generated by Django 2.0.5 on 2018-07-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0008_remove_holiday_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='from_session',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='grant_expire_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='to_session',
        ),
    ]
