# Generated by Django 2.0.5 on 2018-07-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0009_auto_20180718_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='is_optional',
        ),
    ]
