# Generated by Django 2.0.5 on 2018-07-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0010_remove_holiday_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
