# Generated by Django 2.0.5 on 2018-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0012_auto_20180719_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='/home/cloudanalogy/PycharmProjects/attendance_ca/employee_attendance/templates/images/teams/team-1.jpg', upload_to='templates/images/'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type_of_transaction',
            field=models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Granted', 'Granted'), ('Availed', 'Availed'), ('Encashed', 'Encashed'), ('Lapsed', 'Lapsed'), ('Closing Balance', 'Closing Balance')], max_length=30, null=True),
        ),
    ]
