# Generated by Django 2.0.5 on 2018-07-30 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0014_auto_20180730_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('bill', models.ImageField(upload_to='')),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Availed', 'Availed')], max_length=256)),
                ('applied_date', models.DateField(default=datetime.date.today)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256, null=True, unique=True)),
                ('description', models.TextField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_attendance.ReimbursementType'),
        ),
    ]
