# Generated by Django 2.0.5 on 2018-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0016_auto_20180730_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
