# Generated by Django 2.0.4 on 2018-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance', '0018_auto_20180731_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendances', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Holidays', 'verbose_name_plural': 'Holiday'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leaves', 'verbose_name_plural': 'Leave'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Logs', 'verbose_name_plural': 'Log'},
        ),
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'verbose_name': 'Reimbursements', 'verbose_name_plural': 'Reimbursement'},
        ),
        migrations.AlterModelOptions(
            name='reimbursementtype',
            options={'verbose_name': 'Reimbursement Types', 'verbose_name_plural': 'Reimbursement Type'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='attendance',
            name='record_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='record_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='record_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin HR', 'Admin HR'), ('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('Developer', 'Developer'), ('Intern Developer', 'Intern Developer'), ('QA or Tester', 'QA or Tester')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
